#!/bin/bash

set -ex

echo "Copying figures generated R"
cp Working/Figure*.png figure-images


echo "Copying figures generated by Python"
# Figure 4
cp bcell/spike-domains-glycosylated-accessibility-mutations-glycosites-predicted-epitopes.png figure-images/Figure-4-C.png
cp bcell/spike-domains-bcell-epitopes-colored-by-number-of-sources-predicted-epitopes-tall.png figure-images/Figure-4-D.png
cp bcell/spike-domains-glycosylated-accessibility-mutations-glycosites-predicted-epitopes.pdf figure-images/Figure-4-C.pdf
cp bcell/spike-domains-bcell-epitopes-colored-by-number-of-sources-predicted-epitopes-tall.pdf figure-images/Figure-4-D.pdf
cp structure-visualization/bcell-epitopes-v3.png figure-images/Figure-4-E.png

# Figure 5
pdftk  vaccine-peptides/tables.pdf cat 1-1 output figure-images/Figure-5-A.pdf
pdftk  vaccine-peptides/tables.pdf cat 2-2 output figure-images/Figure-5-B.pdf

# Figure 6
cp tcell-validation/binned-tcell-responses-vs-vaccine-peptides.pdf figure-images/Figure-6-B.pdf

# supp
cp vaccine-peptides/manufacturability-violin-plot.png figure-images/Figure-S8-B.png
pdftk  vaccine-peptides/tables.pdf cat 3-3 output figure-images/Figure-S9-A.pdf
pdftk  vaccine-peptides/tables.pdf cat 4-4 output figure-images/Figure-S9-B.pdf
pdftk  vaccine-peptides/tables.pdf cat 5-5 output figure-images/Figure-S10-A.pdf
pdftk  vaccine-peptides/tables.pdf cat 6-6 output figure-images/Figure-S10-B.pdf


